### ISSUE TITLE
wonky in corners

### ISSUE THREAD

**Issue by 4strid** [cutejs/edgescroll#1]
should check distance to *an* edge, not "distance from the edge", as this results in unpleasant side-to-side scrolling at inappropriate times

**Comment by juliovedovatto** [comment]
Hello @4strid  from the future

I had some unexpected effects implementing your library, so I decide to make small modifications to fit my case.

```js
  var scrollByX  = 0
  var scrollByY = 0

  if (this.clientX <= radius || (this.innerWidth - this.clientX) <= radius) {
    scrollByX = Math.round(velocityX * elapsed / 1000)
  }
  if (this.clientY <= radius || (this.innerHeight - this.clientY) <= radius) {
    scrollByY = Math.round(velocityY * elapsed / 1000)
  }

  window.scrollBy(scrollByX, scrollByY)
```

Basically, I did an extra check to make sure mouse cursor is inside the radius area. 

I'm not sure if this is what you meant, but this solved my case. Sometimes page decided do scroll even if I was not near the radius area. 

(Just leaving it here for other developers who might face the same problem as me)

**Comment by 4strid** [comment]
do you want to just make a pull request 😅 i haven't programmed a computer in a few years so im not *certain* , but this definitely seems like exactly what i prescribed .

**Comment by juliovedovatto** [comment]
@4strid Hey I created a PR to address the issue. Could you take a look?
